- .github/workflows/ci.yml
- pkg/broker/mqtt/mqtt_test.go
- pkg/server/server_test.go
- pkg/testlib/mqtt.go
> [WIP] Add env MacOS and Windows

- pkg/backupapi/backup_directory.go
- pkg/backupapi/client.go
- pkg/backupapi/client_test.go
- pkg/backupapi/file.go
- pkg/backupapi/machine.go
- pkg/backupapi/policy.go
- pkg/backupapi/recovery_point.go
This PR adds backup api client, basic models and authorization header.
Closes #12
> pkg/backupapi: add backup client

- .gitignore
- cmd/agent.go
- go.mod
- go.sum
- pkg/agentversion/agentversion.go
- pkg/agentversion/agentversion_test.go
- pkg/backupapi/machine.go
- pkg/backupapi/machine_test.go
- pkg/server/option.go
- pkg/server/server.go
> Update machine info when starting agent

- go.mod
- go.sum
- pkg/backupapi/machine.go
- pkg/backupapi/machine_test.go
> pkg/backupapi: add os machine id

- pkg/backupapi/recovery_point.go
- pkg/server/server.go
- pkg/server/server_test.go
> Feature/BK-102 - Feature/restore flow

- go.mod
- go.sum
- pkg/backupapi/client.go
- pkg/server/server.go
- pkg/server/server_test.go
After then, server will subscribe to broker server and add more entry to
cron manager for running backup. That will be done in BK-104
Fixes BK-103
> pkg/server: start cron when creating server

- cmd/agent.go
- cmd/backup.go
- cmd/restore.go
- go.mod
- go.sum
- pkg/backupapi/backup_directory.go
- pkg/backupapi/config.go
- pkg/backupapi/config_test.go
- pkg/backupapi/recovery_point.go
- pkg/backupapi/recovery_point_test.go
- pkg/server/server.go
- pkg/server/server_test.go
> Implement client side commands

- go.mod
- go.sum
- pkg/backupapi/machine.go
So it won't return error when it should not.
Fixes BK-134
> pkg/backupapi: upgrade osinfo to latest version

- cmd/agent.go
> set api url when create backupClient

- cmd/root.go
Only log root cmd error in debug mode.
> cmd: better error message

- cmd/agent.go
- pkg/broker/mqtt/mqtt.go
- pkg/broker/mqtt/mqtt_test.go
- pkg/broker/mqtt/option.go
> pkg/broker: allow passing username/password

- cmd/backup.go
> cmd: show directory path when list backup

- cmd/agent.go
> cmd: retry when update machine

- pkg/broker/message.go
- pkg/server/server.go
> pkg/broker,server: handle add/del directory event

- pkg/server/server.go
> pkg/server: notify status online when connected

- cmd/backup.go
- cmd/restore.go
- go.mod
- go.sum
- pkg/backupapi/file.go
- pkg/backupapi/file_test.go
- pkg/backupapi/helper.go
- pkg/backupapi/helper_test.go
- pkg/server/server.go
> Progress report

- go.mod
- go.sum
- pkg/backupapi/client.go
- pkg/backupapi/file.go
- pkg/backupapi/file_test.go
> pkg/server: retry backup if network error

- pkg/backupapi/client.go
- pkg/backupapi/client_test.go
- pkg/backupapi/config_test.go
- pkg/backupapi/file.go
- pkg/backupapi/machine_test.go
- pkg/backupapi/recovery_point_test.go
> pkg/backupapi: allow relative path in server url config

- pkg/backupapi/recovery_point.go
- pkg/broker/message.go
- pkg/server/server.go
Add the name parameter to the backup function
Add recovery_point_type into request body when creating a recovery point
> Add name parameter to the backup function

- pkg/backupapi/helper.go
- pkg/backupapi/helper_test.go
- pkg/backupapi/machine.go
> pkg/backupapi: get outbound ip address

- pkg/backupapi/backup_directory.go
- pkg/backupapi/client_test.go
- pkg/backupapi/config.go
- pkg/backupapi/helper.go
- pkg/backupapi/machine.go
- pkg/backupapi/recovery_point.go
> pkg/backupapi: report error for non-ok status

- pkg/backupapi/client.go
- pkg/backupapi/file.go
- pkg/backupapi/file_test.go
- pkg/backupapi/recovery_point.go
- pkg/server/server.go
File larger than 15MB will be split to parts and upload each part to
server using upload part API.
Fixes BK-169
> pkg/backupapi: add upload multipart for large file

- cmd/agent.go
- cmd/restore.go
- pkg/backupapi/client.go
- pkg/backupapi/recovery_point.go
- pkg/broker/message.go
- pkg/server/server.go
Fix download recovery point
Fix restore flow
> Fix restore

- pkg/server/server.go
> pkg/server: notify server when backup/restore failed

- cmd/backup.go
> cmd: generate restore session key when download recovery point manually

- pkg/server/server.go
> pkg/server: warn when get unknown event

- scripts/README.md
- scripts/linux.sh
- scripts/macos.sh
- scripts/windows.ps1
>  Add scripts install agent

- pkg/backupapi/machine.go
- pkg/backupapi/machine_test.go
> pkg/backupapi: remove machine id

- scripts/linux.sh
Update script support suse, debian
> Update script support suse, debian

- scripts/README.md
- scripts/linux.sh
- scripts/macos.sh
- scripts/windows.ps1
Script check new version before installing
> Script check new version before installing

- pkg/server/server.go
> pkg/server: add reason when notify failed message

- cmd/agent.go
- cmd/root.go
> cmd: make "-addr" a root command flags

- pkg/backupapi/client.go
- pkg/backupapi/file.go
- pkg/server/server.go
Prevent consuming too much memory.
> pkg/backupapi: refactor upload multipart

- scripts/macos.sh
> Fix script for Mac OS

- scripts/windows.ps1
> Fix script for Windows

- .github/workflows/ci.yml
- go.mod
- pkg/backupapi/client.go
- pkg/backupapi/file.go
- pkg/backupapi/recovery_point.go
- pkg/cache/cache.go
- pkg/cache/chunk.go
- pkg/cache/index.go
- pkg/server/server.go
- pkg/support/chown_darwin.go
- pkg/support/chown_unix.go
- pkg/support/chown_unix_test.go
- pkg/support/chown_windows.go
- pkg/support/item_darwin.go
- pkg/support/item_unix.go
- pkg/support/item_windows.go
- pkg/volume/s3/s3.go
Backup/restore with store index in storage
> Storing index storage

- pkg/cache/index.go
- pkg/server/server.go
- pkg/server/server_test.go
Save list file to csv when backup, total size file
> Handle file when backup

- pkg/server/server.go
Send total files backup to server via mqtt
> Send total files backup 

- pkg/backupapi/file.go
- pkg/server/server.go
> Add progress when restore

- cmd/agent.go
- pkg/server/option.go
- pkg/server/server.go
- pkg/server/server_test.go
change topic when show progress
> change topic when show progress

- pkg/backupapi/file.go
- pkg/server/server.go
save chunk to chunk.json when backup (put chunk.json when backup failed)
> save chunk to chunk.json when backup

- pkg/backupapi/file.go
- pkg/storage_vault/s3/s3.go
- fix logic backup chunk support multiple storage
- compare etag of chunk after upload with local
> backup chunk support multiple storage

- pkg/backupapi/client.go
- pkg/backupapi/storage_vault.go
- pkg/storage_vault/s3/s3.go
- Add set max elapsed time for storage s3, client to stop retry after 3 minute
- Change code retry backoff storage vault to lib cenkalti backoff
> Fix retry backoff for storage vault, s3 and client 

- pkg/backupapi/file.go
- pkg/server/server.go
- fix show count items uploading, downloading
- fix show total size of items, total items download
> Fix show progress upload and download

- cmd/backup.go
- pkg/backupapi/recovery_point.go
- pkg/backupapi/recovery_point_test.go
- use command list all recovery points of a directory
> fix command backup list all recovery point

- README.md
- cmd/cleanup_cache.go
- pkg/cache/cache.go
- pkg/server/server.go
- add command check and remove old cache directory 
- schedule check and remove old cache directory
> check and remove old cache directory

- pkg/backupapi/backup_directory.go
- pkg/backupapi/backup_directory_test.go
- pkg/server/server.go
- update size of the directory that are configured to backup to the server via MQTT server
- time interval 15 minutes.
> update size of the directory on machine

- pkg/server/server.go
- fix schedule task check old cache directory after 1 days
- fix schedule task update size of directory on machine after 15 minutes
> fix schedule task after time interval

- pkg/backupapi/storage_vault.go
- pkg/server/server.go
- pkg/storage_vault/s3/s3.go
- when the credential expires, agent will retry to get credential storage vault
> fix retry get credential storage vault

- pkg/backupapi/file.go
- pkg/server/server.go
- while backup the file deleted pass deleted file
> pass deleted file when backup

- pkg/backupapi/storage_vault.go
- pkg/server/server.go
- pkg/storage_vault/s3/s3.go
- pkg/storage_vault/s3/s3_test.go
- pkg/storage_vault/storage.go
- add publish notificiation when percent > 0
- release closes the default pool
- read the body response into a variable
- remove unused field
> handle some errors during backup

- pkg/backupapi/client.go
- pkg/backupapi/file.go
- pkg/server/server.go
- save chunk to chunk.json during backup using channel instead of using mutex
> save chunk during backup using channel

- pkg/backupapi/client.go
- pkg/cache/cache.go
- pkg/server/server.go
- pkg/server/server_test.go
- add machine id to name storing chunk.json, index.json, file.csv on storage s3
> add machine id to storing index storage

- pkg/broker/mqtt/mqtt.go
- change qos mqtt from default 0 to 1
> change qos (quality of service) mqtt

- pkg/backupapi/file.go
- pkg/cache/chunk.go
- pkg/server/server.go
- add length of chunk to chunk.json
> add length of chunk to chunks.json

- pkg/backupapi/file.go
- pkg/cache/chunk.go
- pkg/server/server.go
> change struct of chunk.json

- pkg/server/server.go
- add column size and column chunk
> change struct file.csv

- pkg/backupapi/handle_log.go
- pkg/backupapi/handle_log_test.go
- pkg/cache/cache.go
- pkg/server/server.go
- pkg/server/server_test.go
- pkg/support/path_darwin.go
- pkg/support/path_unix.go
- pkg/support/path_windows.go
- edit path save log file and cache file support multi os
> edit path save log file and cache file support multi os

- pkg/backupapi/storage_vault.go
- when expired, retry get restore session key to continue
> retry get restore session key when expired

- cmd/backup.go
- pkg/backupapi/config.go
- add created at when list recovery point backup cmd
> add infomations in backup cmd

- pkg/server/server.go
- fix get machine id when restore
> fix get machine id when restore

- pkg/server/server.go
- add log when backup and restore
- add notify status failed when restore error
> add log and notify status failed when backup restore
